version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitMcspprod3007Project
  gitServerName: KusiMSCPProd
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
