version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitMcspprod3007Project
  gitServerName: KusiMSCPProd
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
  gitServerName: KusiMSCPProd
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: JMSTest
  version: "1.0"
  gitServerName: KusiMSCPProd
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SSL_JDBC_Test
  version: "1.0"
  gitServerName: KusiMSCPProd
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqagitmcspprod3007.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQAGitMcspprod3007Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqagitmcspprod3007.integrations:JMS_JNDI_SSL
  packages:
  - name: SIQAGitMcspprod3007Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: publisher:publisher
  packages:
  - name: JMSTest
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.siqagitmcspprod3007.integrations:SIQAAdapterFlow
  packages:
  - name: SIQAGitMcspprod3007Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
